kind: pipeline
name: default

steps:

- name: docker
  image: plugins/docker
  settings:
    username: podloveradiator
    password:
      from_secret: docker_password
    repo: podlove/radiator-cms
    tags: latest
  when:
    branch:
      - master
    event:
      - push

- name: docker-dev
  image: plugins/docker
  settings:
    username: podloveradiator
    password:
      from_secret: docker_password
    repo: podlove/radiator-cms
    tags: develop
  when:
    branch:
      - develop
    event:
      - push
